name: Publish to PyPi

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Verify tag and version
      id: verify_version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "TAG_VERSION=$TAG_VERSION"
        SETUP_VERSION=$(python -c 'import source_infuser as psi; print(psi.__version__)')
        echo "SETUP_VERSION=$SETUP_VERSION"
        if [ "$TAG_VERSION" != "$SETUP_VERSION" ]; then
          echo "Tag version ($TAG_VERSION) does not match setup.py version ($SETUP_VERSION)"
          exit 1
        fi

    - name: Run tests
      run: make test

    - name: Build and Upload
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        make release

